const courses = [
 {id:'s1-ue1',semester:1,ue:'UE 1 · 6 ECTS',title:'Introduction à la psychologie',icon:'⌁',desc:'Courants fondateurs, objets d’étude et grands champs de la discipline.',topics:['Courants & thèmes','Champs de la psychologie'],theory:`<h3>Une science, plusieurs regards</h3><p>La psychologie étudie scientifiquement les conduites et les processus mentaux. Un même comportement peut être lu à plusieurs niveaux : biologique, cognitif, affectif, social et développemental. Ces explications ne s’annulent pas ; elles se complètent.</p><h3>Les grands courants</h3><ul><li><b>Structuralisme et fonctionnalisme :</b> décrire la conscience, puis comprendre à quoi servent les processus mentaux.</li><li><b>Béhaviorisme :</b> étudier les comportements observables et les apprentissages par conditionnement.</li><li><b>Psychanalyse :</b> penser le rôle de l’inconscient, des conflits et de l’histoire du sujet.</li><li><b>Cognitivisme :</b> modéliser le traitement de l’information : perception, mémoire, langage, raisonnement.</li><li><b>Humanisme :</b> mettre l’accent sur l’expérience vécue, le sens et l’accomplissement.</li></ul><div class="key-box"><strong>Le réflexe L1</strong><p>Pour chaque théorie, retiens : sa question, sa méthode, ses concepts et ce qu’elle permet — ou non — d’expliquer.</p></div><h3>Les champs</h3><p>Cognitive, sociale, développementale, clinique, travail-ergonomie et neuropsychologie sont des champs distincts, mais tous construisent des hypothèses discutables et cherchent des preuves adaptées.</p>`},
 {id:'s1-ue2',semester:1,ue:'UE 2 · 6 ECTS',title:'Méthodologie & statistiques',icon:'∑',desc:'Décrire des données, poser une hypothèse et raisonner avec rigueur.',topics:['Statistiques descriptives','Méthodes scientifiques'],theory:`<h3>Décrire avant d’expliquer</h3><p>Une <b>population</b> est l’ensemble visé ; l’<b>échantillon</b> est le groupe observé. Une variable peut être qualitative ou quantitative. Moyenne, médiane et mode décrivent la tendance centrale ; étendue, variance et écart-type décrivent la dispersion.</p><div class="key-box"><strong>Attention à la moyenne</strong><p>Elle est sensible aux valeurs extrêmes. Une distribution très asymétrique se résume souvent mieux par la médiane.</p></div><h3>La démarche scientifique</h3><p>On part d’une question, on formule une hypothèse réfutable, on opérationnalise les concepts en variables, on recueille des observations, puis on interprète avec prudence. Une corrélation indique une covariation, jamais à elle seule une causalité.</p><h3>Validité et éthique</h3><p>La validité interne concerne la solidité de l’explication causale ; la validité externe, sa généralisation. Consentement, confidentialité, droit de retrait et débriefing protègent les participants.</p>`},
 {id:'s1-ue3',semester:1,ue:'UE 3 · 6 ECTS',title:'Psychologie & société',icon:'◎',desc:'Culture, création et évolution : trois façons de penser l’humain en contexte.',topics:['Interculturel','Psychologie & art','Évolutionnisme'],theory:`<h3>Culture et psychisme</h3><p>La psychologie interculturelle compare les processus selon les contextes culturels. Elle distingue notamment les approches <b>étique</b> (chercher des dimensions communes) et <b>émique</b> (comprendre de l’intérieur). Elle invite à éviter l’ethnocentrisme.</p><h3>Art et expérience esthétique</h3><p>Créer et percevoir une œuvre mobilisent attention, émotion, mémoire, imagination et normes sociales. L’art n’est donc pas un simple « stimulus » : le sens dépend aussi du sujet et de son contexte.</p><h3>Perspective évolutionniste</h3><p>Elle demande si certains mécanismes psychologiques ont pu être favorisés parce qu’ils répondaient à des problèmes récurrents de survie ou de reproduction. Une explication évolutionniste est une hypothèse à tester, pas une justification morale ni l’idée que tout est inné.</p><div class="key-box"><strong>Question utile</strong><p>Ce résultat décrit-il un universel humain, une pratique culturelle particulière, ou leur interaction ?</p></div>`},
 {id:'s1-ue4',semester:1,ue:'UE 4 · 6 ECTS',title:'Sciences humaines',icon:'✦',desc:'Le jeu et l’éducation comme laboratoires du développement et du lien social.',topics:['Le jeu','L’éducation'],theory:`<h3>Pourquoi joue-t-on ?</h3><p>Le jeu est à la fois activité libre, espace réglé et simulation. Il soutient exploration, apprentissage, régulation émotionnelle, imagination et socialisation. Le jeu symbolique permet notamment de représenter une chose par une autre.</p><h3>Éduquer, transmettre, émanciper</h3><p>L’éducation ne se limite pas à l’école. Elle articule apprentissages, normes, interactions et institutions. Les attentes de l’enseignant, le sentiment d’efficacité personnelle, la motivation et les inégalités de contexte influencent l’expérience scolaire.</p><div class="key-box"><strong>À relier</strong><p>Jeu et éducation montrent ensemble que l’on apprend en agissant avec des objets, des règles et d’autres personnes.</p></div><h3>Regarder sans réduire</h3><p>Une analyse psychologique gagne à dialoguer avec sociologie, philosophie, histoire et sciences de l’éducation : l’individu n’existe jamais hors de ses milieux.</p>`},
 {id:'s1-ue5',semester:1,ue:'UE 5 · 3 ECTS',title:'Langue vivante I',icon:'Aa',desc:'Comprendre le vocabulaire universitaire et scientifique dans une autre langue.',topics:['Anglais, allemand, espagnol ou italien','TD & plateforme'],theory:`<h3>La langue de la recherche</h3><p>L’objectif n’est pas seulement grammatical : il faut repérer la structure d’un résumé scientifique, identifier question, méthode, résultats et conclusion, puis expliquer une idée clairement.</p><h3>Vocabulaire stratégique</h3><ul><li><b>sample</b> : échantillon ; <b>finding</b> : résultat ; <b>evidence</b> : élément de preuve.</li><li><b>bias</b> : biais ; <b>survey</b> : enquête ; <b>reliable</b> : fiable.</li><li><b>to assess</b> : évaluer ; <b>to account for</b> : expliquer / rendre compte.</li></ul><div class="key-box"><strong>Méthode</strong><p>Apprends les mots dans une phrase et par familles. Dix cartes contextualisées valent mieux qu’une liste de cinquante mots isolés.</p></div>`},
 {id:'s1-ue6',semester:1,ue:'UE 6 · 3 ECTS',title:'Outils universitaires I',icon:'↗',desc:'Prendre des notes, chercher des sources et organiser son travail.',topics:['MTU','Recherche documentaire','Numérique'],theory:`<h3>Passer du cours à la connaissance</h3><p>Une bonne note de cours sélectionne et hiérarchise. Dans les 24 heures, complète les zones floues, transforme les titres en questions et produis un résumé sans regarder.</p><h3>Chercher une source</h3><p>Traduis ton sujet en mots-clés et synonymes, utilise les opérateurs AND/OR, puis évalue auteur, date, revue, méthode et bibliographie. Un article scientifique n’a pas le même statut qu’un billet d’opinion.</p><div class="key-box"><strong>Cycle efficace</strong><p>Cours → clarification → fiche-question → rappel actif → correction → rappel espacé.</p></div><h3>Hygiène numérique</h3><p>Nomme clairement les fichiers, sauvegarde à deux endroits, cite tes sources dès la prise de notes et distingue citation, paraphrase et idée personnelle.</p>`},
 {id:'s2-ue1',semester:2,ue:'UE 1 · 6 ECTS',title:'Développement & cognition',icon:'◌',desc:'Grandes étapes de la vie, mémoire, attention et perception.',topics:['Étapes du développement','Mémoire · attention · perception'],theory:`<h3>Le développement, un processus</h3><p>Le développement résulte d’interactions entre maturation biologique, expériences et contexte social. Il peut être continu ou connaître des réorganisations. Les trajectoires sont variables : une étape moyenne n’est pas une norme rigide.</p><h3>Percevoir et sélectionner</h3><p>La perception construit une interprétation à partir des signaux sensoriels et des connaissances. L’attention sélectionne certaines informations ; ses ressources sont limitées.</p><h3>Les systèmes de mémoire</h3><p>La mémoire de travail maintient et manipule brièvement l’information. La mémoire à long terme inclut notamment mémoire épisodique (événements), sémantique (connaissances) et procédurale (savoir-faire). Encoder, consolider et récupérer sont trois opérations distinctes.</p><div class="key-box"><strong>À retenir</strong><p>Oublier peut venir d’un encodage faible ou d’un problème de récupération — pas forcément d’une information « effacée ».</p></div>`},
 {id:'s2-ue2',semester:2,ue:'UE 2 · 6 ECTS',title:'Psychologie sociale & clinique',icon:'☍',desc:'Influence du groupe et premiers repères de psychopathologie psychanalytique.',topics:['Influence sociale','Psychopathologie de l’adulte'],theory:`<h3>L’influence sociale</h3><p>La <b>conformité</b> rapproche une réponse de celle du groupe, par besoin d’être accepté ou de disposer d’une information juste. L’<b>obéissance</b> implique une autorité. Une minorité cohérente peut aussi produire de l’innovation.</p><h3>Clinique et psychopathologie</h3><p>La démarche clinique s’intéresse à la singularité du sujet, à son histoire et au sens de ses symptômes. Dans la perspective psychanalytique, le conflit psychique, l’inconscient et les mécanismes de défense structurent la compréhension.</p><div class="key-box"><strong>Ne pas confondre</strong><p>Un mécanisme de défense est un mode de protection psychique généralement inconscient ; une stratégie de coping désigne plutôt un effort pour faire face à une situation stressante.</p></div><h3>Une posture prudente</h3><p>Expliquer n’est ni étiqueter ni diagnostiquer à distance. Les modèles sont des cadres de compréhension et leurs concepts doivent être situés.</p>`},
 {id:'s2-ue3',semester:2,ue:'UE 3 · 6 ECTS',title:'Méthodo, neurosciences & ergonomie',icon:'⌇',desc:'Expérimenter, comprendre le neurone et adapter le travail à l’humain.',topics:['Méthode expérimentale','Communication neuronale','Ergonomie'],theory:`<h3>Tester une relation causale</h3><p>L’expérimentateur manipule une variable indépendante, mesure une variable dépendante et contrôle les facteurs confondants. La répartition aléatoire aide à rendre les groupes comparables. Le groupe contrôle fournit un point de comparaison.</p><h3>Le neurone communique</h3><p>Le potentiel d’action est un signal électrique tout-ou-rien qui se propage le long de l’axone. À la synapse chimique, des neurotransmetteurs modifient la probabilité d’activation de la cellule suivante. Excitateur et inhibiteur décrivent un effet, pas une molécule « bonne » ou « mauvaise ».</p><h3>L’ergonomie</h3><p>Elle cherche à adapter les situations de travail aux personnes. Elle distingue le travail prescrit du travail réel et analyse activité, contraintes, variabilité et stratégies.</p><div class="key-box"><strong>Fil rouge</strong><p>Dans les trois matières, on construit un dispositif pour observer sans perdre de vue la situation réelle.</p></div>`},
 {id:'s2-ue4',semester:2,ue:'UE 4 · 6 ECTS',title:'Approfondissements en psychologie',icon:'⤢',desc:'Contrôle cognitif, thérapies, propagande et socialisation de l’enfant.',topics:['Contrôle cognitif','Approches thérapeutiques','Propagande','Socialisation'],theory:`<h3>Garder le cap mental</h3><p>Le contrôle cognitif permet d’inhiber une réponse dominante, de changer de règle et de mettre à jour l’information pertinente. Les tâches de Stroop illustrent le conflit entre une lecture automatisée et la consigne.</p><h3>Plusieurs approches thérapeutiques</h3><p>Les approches psychodynamiques travaillent conflits et répétitions ; les thérapies cognitivo-comportementales ciblent apprentissages, pensées et comportements ; les approches humanistes privilégient expérience, relation et ressources. Les pratiques s’évaluent selon des objectifs et des méthodes explicites.</p><h3>Propagande et manipulation</h3><p>Répétition, cadrage, appel émotionnel, engagement progressif et crédibilité de la source peuvent orienter jugements et conduites. Être influencé n’implique pas d’être passif ou irrationnel.</p><h3>Socialisation</h3><p>L’enfant intériorise normes et rôles par la famille, les pairs, l’école et les médias. Il est aussi acteur : il interprète et transforme ce qu’il reçoit.</p>`},
 {id:'s2-ue5',semester:2,ue:'UE 5 · 3 ECTS',title:'Langue vivante II',icon:'Ab',desc:'Lire, synthétiser et présenter un contenu psychologique.',topics:['Compréhension scientifique','Expression orale'],theory:`<h3>Lire par couches</h3><p>Commence par titre, résumé, intertitres et figures. Formule la question de recherche. Lis ensuite méthode et discussion pour vérifier ce que les données autorisent réellement à conclure.</p><h3>Présenter sans traduire mot à mot</h3><p>Une présentation claire suit : contexte → question → méthode → résultat central → limite. Utilise des connecteurs simples et exacts plutôt qu’un vocabulaire spectaculaire mais fragile.</p><div class="key-box"><strong>Formules utiles</strong><p><i>The study aims to… / The results suggest… / One limitation is… / This finding does not imply that…</i></p></div><h3>Esprit critique</h3><p>Distingue toujours le résultat observé de l’interprétation proposée. Le conditionnel est parfois la forme la plus scientifique.</p>`},
 {id:'s2-ue6',semester:2,ue:'UE 6 · 3 ECTS',title:'Outils & projet professionnel',icon:'◇',desc:'Recherche documentaire, numérique et découverte des métiers.',topics:['Documentation','Numérique','PPPE'],theory:`<h3>Construire une veille</h3><p>Garde la requête utilisée, les critères de sélection et les références complètes. Classe les sources par question plutôt que par format. Un tableau « idée / preuve / limite / référence » facilite la synthèse.</p><h3>Le projet professionnel</h3><p>Le titre de psychologue nécessite en France une licence de psychologie puis un master de psychologie comprenant un stage professionnel. Mais la licence développe aussi des compétences transférables : analyse, enquête, rédaction, travail en équipe et traitement de données.</p><div class="key-box"><strong>Explorer concrètement</strong><p>Pour un métier : missions réelles, publics, lieux, formation, contraintes et compétences. Un entretien avec un professionnel vaut mieux qu’une image vague du métier.</p></div><h3>Stage facultatif</h3><p>S’il est choisi, prépare une question d’observation et un retour réflexif. Respecte confidentialité, limites de rôle et cadre institutionnel.</p>`}
];

const questions=[
 {q:'Une corrélation élevée entre deux variables permet-elle de conclure à une causalité ?',a:['Oui, toujours','Oui, si l’échantillon est grand','Non, pas à elle seule'],good:2,why:'Une troisième variable ou une causalité inverse restent possibles.'},
 {q:'Quelle mémoire contient les connaissances générales, comme la capitale d’un pays ?',a:['Mémoire épisodique','Mémoire sémantique','Mémoire procédurale'],good:1,why:'La mémoire sémantique concerne les concepts et connaissances générales.'},
 {q:'Dans une expérience, que manipule le chercheur ?',a:['La variable indépendante','La variable dépendante','L’écart-type'],good:0,why:'La variable dépendante est mesurée ; la variable indépendante est manipulée.'},
 {q:'Se conformer pour être accepté par le groupe relève surtout de…',a:['L’influence normative','L’influence génétique','La validité externe'],good:0,why:'L’influence normative répond au besoin d’approbation et d’appartenance.'},
 {q:'Le potentiel d’action est…',a:['Un signal électrique tout-ou-rien','Une hormone','Un souvenir moteur'],good:0,why:'Il se propage le long de l’axone avant la transmission synaptique.'},
 {q:'Quel indicateur est le moins sensible aux valeurs extrêmes ?',a:['La moyenne','La médiane','La variance'],good:1,why:'La médiane dépend du rang central et résiste mieux aux extrêmes.'},
 {q:'Dans l’effet Stroop, il faut principalement…',a:['Consolider un souvenir','Inhiber une réponse automatisée','Se conformer au groupe'],good:1,why:'Il faut inhiber la lecture du mot pour nommer la couleur de l’encre.'},
 {q:'L’approche émique cherche surtout à…',a:['Comprendre une culture de l’intérieur','Trouver uniquement des universaux','Mesurer des neurones'],good:0,why:'Elle étudie les significations propres à un contexte culturel.'},
 {q:'En ergonomie, le travail réel désigne…',a:['La fiche de poste','Ce que la personne fait effectivement','Le travail idéal'],good:1,why:'L’activité réelle s’ajuste aux contraintes, aléas et objectifs concurrents.'},
 {q:'Pour mémoriser durablement, le plus efficace est de…',a:['Relire cinq fois de suite','Surligner tout le cours','Se tester à intervalles espacés'],good:2,why:'Le rappel actif et l’espacement renforcent la récupération future.'}
];

const grid=document.querySelector('#courseGrid'), dialog=document.querySelector('#courseDialog'), content=document.querySelector('#courseContent'), quizDialog=document.querySelector('#quizDialog'), quizContent=document.querySelector('#quizContent');
let progress=new Set(JSON.parse(localStorage.getItem('psychoProgress')||'[]')); let quizDone=Number(localStorage.getItem('psychoQuizDone')||0);

function renderCourses(filter='all'){
 grid.innerHTML=courses.filter(c=>filter==='all'||String(c.semester)===filter).map(c=>`<article class="course-card ${progress.has(c.id)?'is-done':''}" data-id="${c.id}"><div class="card-top"><span class="ue-tag">S${c.semester} · ${c.ue}</span><b>${c.icon}</b></div><h3>${c.title}</h3><p>${c.desc}</p><footer><span>${c.topics.length} chapitres</span><button aria-label="Ouvrir ${c.title}">→</button></footer></article>`).join('');
 grid.querySelectorAll('.course-card').forEach(el=>el.addEventListener('click',()=>openCourse(el.dataset.id)));
}
function openCourse(id){
 const c=courses.find(x=>x.id===id); progress.add(id); saveProgress();
 content.innerHTML=`<div class="dialog-hero"><span class="ue-tag">Semestre ${c.semester} · ${c.ue}</span><h2>${c.title}</h2><p>${c.desc}</p></div><div class="dialog-body"><p class="eyebrow"><span></span> Synthèse théorique</p>${c.theory}<h3>Au programme</h3><ul>${c.topics.map(t=>`<li>${t}</li>`).join('')}</ul><button class="check-course" data-check>✓ Marquer cette UE comme commencée</button></div>`;
 dialog.showModal(); content.querySelector('[data-check]').onclick=()=>{dialog.close();toast('Progression enregistrée — joli départ !')};
}
function saveProgress(){localStorage.setItem('psychoProgress',JSON.stringify([...progress]));updateDashboard();renderCourses(document.querySelector('.semester-tabs .active').dataset.filter)}
function updateDashboard(){const pct=Math.round(progress.size/courses.length*100);document.querySelector('#progressCount').textContent=`${progress.size} / 12`;document.querySelector('#quizCount').textContent=`${quizDone} quiz${quizDone>1?'s':''}`;document.querySelector('#progressBar').style.width=pct+'%';document.querySelector('#progressLabel').textContent=pct===0?'C’est le bon jour pour commencer.':pct===100?'Tour complet — place à la répétition !':`${pct}% du terrain exploré. Continue !`}
document.querySelectorAll('.semester-tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.semester-tabs .active').classList.remove('active');b.classList.add('active');renderCourses(b.dataset.filter)});
document.querySelector('[data-close]').onclick=()=>dialog.close(); dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
document.querySelectorAll('[data-open-quiz]').forEach(b=>b.onclick=startQuiz);document.querySelector('[data-close-quiz]').onclick=()=>quizDialog.close();quizDialog.onclick=e=>{if(e.target===quizDialog)quizDialog.close()};
document.querySelector('[data-surprise]').onclick=()=>openCourse(courses[Math.floor(Math.random()*courses.length)].id);
function startQuiz(){let picked=[...questions].sort(()=>Math.random()-.5).slice(0,5),index=0,score=0;if(!quizDialog.open)quizDialog.showModal();show();function show(){const item=picked[index];quizContent.innerHTML=`<div class="quiz-wrap"><div class="quiz-meta"><span>Quiz minute</span><span>${index+1} / ${picked.length}</span></div><h2>Teste ta mémoire</h2><p class="quiz-question">${item.q}</p><div class="answers">${item.a.map((a,i)=>`<button class="answer" data-i="${i}">${a}</button>`).join('')}</div><div class="feedback"></div></div>`;quizContent.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(b,item));}function answer(btn,item){const chosen=Number(btn.dataset.i),all=quizContent.querySelectorAll('.answer');all.forEach(b=>b.disabled=true);all[item.good].classList.add('correct');if(chosen!==item.good)btn.classList.add('wrong');else score++;const feed=quizContent.querySelector('.feedback');feed.innerHTML=`<b>${chosen===item.good?'Exact !':'Pas tout à fait.'}</b> ${item.why}<br><button class="next-question">${index===picked.length-1?'Voir mon score':'Question suivante →'}</button>`;feed.querySelector('button').onclick=()=>{index++;index<picked.length?show():finish()}}function finish(){quizDone++;localStorage.setItem('psychoQuizDone',quizDone);updateDashboard();quizContent.innerHTML=`<div class="quiz-wrap quiz-result"><span class="eyebrow">Session terminée</span><p class="big-score">${score}/5</p><h2>${score>=4?'Mémoire affûtée !':score>=2?'Ça prend forme.':'On consolide ?'}</h2><p>${score>=4?'Reviens demain pour espacer le rappel.':'Relis les explications, puis retente sans regarder.'}</p><button class="next-question" data-retry>Rejouer</button></div>`;quizContent.querySelector('[data-retry]').onclick=startQuiz}}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
renderCourses();updateDashboard();
